### ISSUE TITLE
countryfile lookup fails

### ISSUE THREAD

**Issue by CyDFect** [dh1tw/pyhamtools#11]
The countryfile lookup fails, because the country 502 "Macedonia" became "North Macedonia".
The error can be fixed by changing Macedonia to New Macedonia in the countryfilemapping.json

73, DG5YHK

**Comment by dh1tw** [comment]
cool - you are completely right. I will change Macedonia to North Macedonia. I will let you know here when I have uploaded the new version to pypi.

**Comment by dh1tw** [comment]
My apologies that it took so long, but now version 0.7.3 is available with Macedonia updated to "North Macedonia"
