### ISSUE TITLE
Country names have changed, leading to KeyErrors.

### ISSUE THREAD

**Issue by adrianboyko** [dh1tw/pyhamtools#12]
I'm not sure where the change was made (maybe in some external system that you depend on) but two country names were updated and countryfilemapping.json needs to be likewise updated to avoid KeyErrors. The required changes are:

* `"Swaziland"` -> `"Kingdom of eSwatini"`
* `"Macedonia"` -> `"North Macedonia"`

These are the new names of these two countries. Note that the capitalization in "Kingdom of eSwatini" is not a typo.

**Comment by dh1tw** [comment]
Hey @adrianboyko,
right - I must have missed the name change of Swaziland. I'll update the library this weekend. `Macedonia` got renamed to `North Macedonia` in [version 0.7.2](https://pyhamtools.readthedocs.io/en/latest/changelog.html). Can you confirm that this is still an issue for you running pyHamtools >= 0.7.2 ?

**Comment by adrianboyko** [comment]
I downgraded to 0.7.0 while diagnosing the problem, which is why I ran into Macedonia -- sorry for the false alarm on that particular value. So, it looks like Swaziland is the only value that needs to be updated for 0.7.4. Thanks!

**Comment by dh1tw** [comment]
Hey @adrianboyko,
I just published pyhamtools 0.7.4, renaming `Swaziland` into`Kingdom of eSwatini`. You should be able to update the package with `pip install --upgrade pyhamtools==0.7.4` 

Thanks again for opening this issue. If something doesn't work as expected, don't hesitate to reopen it.
