### ISSUE TITLE
Deserializing json lookup data stored in redis breaks due to bad escaping

### ISSUE THREAD

**Issue by dh1tw** [dh1tw/pyhamtools#16]
Lookup data (e.g. the clublog XML definitions) can be stored in Redis for better concurrent access amongst several applications on the server. The data is stored in the JSON format in Redis. On access, the data is retrieved and converted back from JSON into a native Python object. 

This works actually well, as long as the serialized data does not contain an apostrophe (inverted comma) or a quotation mark. I found recently this problem while going through the logs of DXHeat. The  country name **Cote d'Ivoire** (Ivery Coast) (ADIF ID 428) caused pyhamtools to through an execption whenever the corresponding country information was read from redis.

**Comment by dh1tw** [comment]
fixed in version v0.7.3

**Comment by df7cb** [comment]
(Fwiw, if that was supposed to be "fixed in v0.7.5", I can't see that yet.)

**Comment by dh1tw** [comment]
well observed @df7cb :-) Now version v0.7.5 is also published on [pypi](https://pypi.org/project/pyhamtools/)

**Comment by df7cb** [comment]
Thanks!
(I was looking at github, though.)
