### ISSUE TITLE
Problems with RBx preffix.

### ISSUE THREAD

**Issue by EB1TR** [dh1tw/pyhamtools#17]
Hello Tobi. Thanks for your amazing work with the library.

Recently I'm using the method "get_all" with ALL RBx preffix.

This is the ressult of the method:

```
>>> cic = Callinfo(my_lookuplib1)
>>> print(cic.get_all('rb4nb'))
{'country': 'INVALID'}
>>> print(cic.get_all('rb1aa'))
{'country': 'INVALID'}
```

Thanks in advance.

73 & DX!

**Comment by dh1tw** [comment]
Hey Fabian,

are you sure that **RB** is actually a valid prefix for European Russia? [Wikipedia](https://en.wikipedia.org/wiki/Call_signs_in_Russia) says:

```
Russia uses the following 1-letter and 2-letter prefixes in amateur radio call signs for normal operation: R, RA, RK, RN, RU, RV, RW, RX, RZ, and UA. Any of these prefixes can be used in any of Russia's federal subjects. The other prefixes are reserved for special operation.
```

Your lookup is most likely failing because the underlying Lookuplib can not resolve the callsigns `RB1AA` or `RB4NB`. What lookuplib are you using?

73 Tobi

**Comment by EB1TR** [comment]
Hi Tobi.!

I don't know if RB is a valid preffix, but daily we have spots of RB4NB and, if you don't have an exception, the scripts go down!

I'm using ClubLog, if I use CountryFiles RB4NB works fine (but have OTHER problems). :(

**Comment by dh1tw** [comment]
Hey Fabian,
I just checked `RB4NB` with the [Clublog Calltester](https://clublog.org/test.php?call=RB4NB&year=2021&month=6&day=13&hour=00&minute=14) and it returned:

```
For QSOs on 2021-06-13 00:14...
RB4NB maps to INVALID
Not valid for DXCC on this date
```

Either `RB4NB` is a pirate or the callsign is indeed not covered by a Clublog exception. My recommendation would be to open a ticket at the [clublog helpdesk](https://clublog.freshdesk.com). The Clublog guys are very responsive and should be able to solve the mystery within a few hours.

**Comment by dh1tw** [comment]
I assume we can close this issue, since it's related to the Clublog exceptions, rather than the callsign algorithms from pyhamtools. If you discover other callsigns, that are not properly decoded, please open another issue! Very much appreciated!
