### ISSUE TITLE
Please drop usage of "future" (and support of Python 2.7)

### ISSUE THREAD

**Issue by a-detiste** [dh1tw/pyhamtools#26]
Hi,

Future is not compatible with Python 3.12 and will likely never be.
It's simpler to move all the project away this huge library.

Please consider remove it's usage from yor project & publish a 3.12 -compatible release.

`python3-future` is being removed from Debian

> from future.utils

Greetings

**Comment by dh1tw** [comment]
yeah, I agree. it's time to deprecate Python 2.7 support

**Comment by dh1tw** [comment]
Today I released v.0.9.0 which supports Python 3.12 and deprecates support for Python 2.7 and Python 3.5.

**Comment by a-detiste** [comment]
Thanks.
