### ISSUE TITLE
'countryfile' lookups fail

### ISSUE THREAD

**Issue by g0ukb** [dh1tw/pyhamtools#5]
All Callsign lookups fall - this is because in Novemember the name for DXCC entity 016 ZL9 changed from Auckland and Campbell Is. to  New Zealand Subantarctic Islands. So the pyhamtools callsign dictionary builder fails. This can be fixed by adding  ',"N.Z. Subantarctic Is.":16' to countryfilemapping.json

**Comment by dh1tw** [comment]
thanks @g0ukb for reporting. I have updated the countrymapping.json file and pushed a new release to pypi (pyhamtools 0.5.3).
