### ISSUE TITLE
get_eqsl_users() fails 404

### ISSUE THREAD

**Issue by g0ukb** [dh1tw/pyhamtools#6]
The URL www.eqsl.cc/QSLCard/DownloadedFiles/AGMemberlist.txt is no longer valid. I have not been able to find out whether:
   this is a temporary problem
   eqsl have changed their web-structure and location of this file
   eqsl have changed their policy and no longer support user querying

**Comment by g0ukb** [comment]
Closed because the eqsl page is back up - I must have just been unlucky testing this when the page was down temporarily.

**Comment by dh1tw** [comment]
it's indeed a problem. The eqsl.cc member list somehow only is available sporadically. I also get frequently an error that the file is not available, but then on other days, the file seems to be there again.
