### ISSUE TITLE
Bytes need conversion to string

### ISSUE THREAD

**Issue by marcusj** [dh1tw/pyhamtools#7]
Need to change

download_file.write(response.content)

to

download_file.write(response.content.decode("ascii"))

in lookuplib.py (I'm running Python 3.5)

73 EA5IGC

**Comment by dh1tw** [comment]
Hi, 
officially PyHamtools only support Python 2.7 / 2.8.

I will have a look at your issue. Which Operating System are you working on? 

What is the specific reason why you want to change it to write it in ASCII?

**Comment by marcusj** [comment]
I'm using Ubuntu 16.04 LTS 64 bit.

I chose ASCII because when I stopped it in the debugger just before executing this line, the response object said the encoding was 'probably ASCII'

**Comment by dh1tw** [comment]
this issue has been fixed with pyhamtools 0.6.0. pyhamtools supports now python 2.7 and > 3.4
